import type { ModelAsset, ModelId } from "@/types/models";

const originalLicense = {
  source: "original",
  author: "Vincent Zhou / Project",
  license: "Original project asset",
  url: "",
} as const;

export const modelRegistry = {
  "vincent-hero": {
    id: "vincent-hero",
    type: "player",
    path: "/models/player/vincent-hero.glb",
    available: true,
    fallbackType: "hero-adventurer",
    scale: 1,
    positionOffset: [0, 0, 0],
    rotationOffset: [0, 0, 0],
    compression: "none",
    preloadDistance: Number.POSITIVE_INFINITY,
    animations: { idle: "Idle", walk: "Walk", interact: "Interact" },
    license: originalLicense,
  },
  "data-sage": {
    id: "data-sage",
    type: "npc",
    path: "/models/npc/data-sage.glb",
    available: true,
    fallbackType: "data-sage-procedural",
    scale: 1,
    positionOffset: [0, 0, 0],
    rotationOffset: [0, 0, 0],
    compression: "none",
    preloadDistance: 13,
    animations: { idle: "Idle", greet: "Greet", interact: "Interact", hover: "Hover" },
    license: originalLicense,
  },
  "robotics-scout": {
    id: "robotics-scout",
    type: "npc",
    path: "/models/npc/robotics-scout.glb",
    available: true,
    fallbackType: "robotics-scout-procedural",
    scale: 1,
    positionOffset: [0, 0, 0],
    rotationOffset: [0, 0, 0],
    compression: "none",
    preloadDistance: 13,
    animations: { idle: "Idle", greet: "Scan", interact: "Interact", hover: "Hover" },
    license: originalLicense,
  },
  "guild-master": {
    id: "guild-master",
    type: "npc",
    path: "/models/npc/guild-master.glb",
    available: false,
    fallbackType: "guild-master-procedural",
    scale: 1,
    positionOffset: [0, 0, 0],
    rotationOffset: [0, 0, 0],
    compression: "none",
    preloadDistance: 12,
    animations: { idle: "Idle", greet: "Greet", interact: "Interact" },
    license: originalLicense,
  },
  "insight-librarian": {
    id: "insight-librarian",
    type: "npc",
    path: "/models/npc/insight-librarian.glb",
    available: false,
    fallbackType: "insight-librarian-procedural",
    scale: 1,
    positionOffset: [0, 0, 0],
    rotationOffset: [0, 0, 0],
    compression: "none",
    preloadDistance: 12,
    animations: { idle: "Idle", greet: "Greet", interact: "Interact", hover: "Hover" },
    license: originalLicense,
  },
  "career-fog-dragon": {
    id: "career-fog-dragon",
    type: "boss",
    path: "/models/boss/career-fog-dragon.glb",
    available: true,
    fallbackType: "career-fog-dragon-procedural",
    scale: 1,
    positionOffset: [0, 0, 0],
    rotationOffset: [0, 0, 0],
    compression: "none",
    preloadDistance: 14,
    animations: { bossIdle: "Idle", pulse: "Pulse", bossInteract: "Roar" },
    license: originalLicense,
  },
  "contact-portal": {
    id: "contact-portal",
    type: "portal",
    path: "/models/portal/contact-portal.glb",
    available: false,
    fallbackType: "portal-procedural",
    scale: 1,
    positionOffset: [0, 0, 0],
    rotationOffset: [0, 0, 0],
    compression: "none",
    preloadDistance: 12,
    animations: { idle: "Idle", pulse: "Pulse", portalInteract: "Activate" },
    license: originalLicense,
  },
  "guide-spirit": {
    id: "guide-spirit",
    type: "npc",
    path: "/models/npc/guide-spirit.glb",
    available: false,
    fallbackType: "guide-spirit-procedural",
    scale: 1,
    positionOffset: [0, 0, 0],
    rotationOffset: [0, 0, 0],
    compression: "none",
    preloadDistance: 12,
    animations: { idle: "Idle", hover: "Hover", interact: "Interact" },
    license: originalLicense,
  },
  sword: {
    id: "sword",
    type: "common",
    path: "/models/common/sword.glb",
    available: false,
    fallbackType: "none",
    scale: 1,
    positionOffset: [0, 0, 0],
    rotationOffset: [0, 0, 0],
    compression: "none",
    preloadDistance: 0,
    animations: {},
    license: originalLicense,
  },
  shield: {
    id: "shield",
    type: "common",
    path: "/models/common/shield.glb",
    available: false,
    fallbackType: "none",
    scale: 1,
    positionOffset: [0, 0, 0],
    rotationOffset: [0, 0, 0],
    compression: "none",
    preloadDistance: 0,
    animations: {},
    license: originalLicense,
  },
  cape: {
    id: "cape",
    type: "common",
    path: "/models/common/cape.glb",
    available: false,
    fallbackType: "none",
    scale: 1,
    positionOffset: [0, 0, 0],
    rotationOffset: [0, 0, 0],
    compression: "none",
    preloadDistance: 0,
    animations: {},
    license: originalLicense,
  },
  lamp: {
    id: "lamp",
    type: "common",
    path: "/models/common/lamp.glb",
    available: false,
    fallbackType: "none",
    scale: 1,
    positionOffset: [0, 0, 0],
    rotationOffset: [0, 0, 0],
    compression: "none",
    preloadDistance: 0,
    animations: {},
    license: originalLicense,
  },
  tree: {
    id: "tree",
    type: "common",
    path: "/models/common/tree.glb",
    available: false,
    fallbackType: "none",
    scale: 1,
    positionOffset: [0, 0, 0],
    rotationOffset: [0, 0, 0],
    compression: "none",
    preloadDistance: 0,
    animations: {},
    license: originalLicense,
  },
  crate: {
    id: "crate",
    type: "common",
    path: "/models/common/crate.glb",
    available: false,
    fallbackType: "none",
    scale: 1,
    positionOffset: [0, 0, 0],
    rotationOffset: [0, 0, 0],
    compression: "none",
    preloadDistance: 0,
    animations: {},
    license: originalLicense,
  },
} as const satisfies Record<ModelId, ModelAsset>;

const failedModelIds = new Set<ModelId>();
const warnedModelIds = new Set<ModelId>();

export function getModelAsset(modelId: ModelId): ModelAsset {
  return modelRegistry[modelId];
}

export function hasModelFailed(modelId: ModelId) {
  return failedModelIds.has(modelId);
}

export function markModelFailed(modelId: ModelId, error: unknown) {
  failedModelIds.add(modelId);
  if (warnedModelIds.has(modelId)) return;
  warnedModelIds.add(modelId);
  console.warn(`[models] Falling back for "${modelId}" because its GLB could not be loaded.`, error);
}

export function canLoadModel(modelId: ModelId) {
  const asset = getModelAsset(modelId);
  return asset.available && !hasModelFailed(modelId);
}
